In [10]:
import tensorflow.experimental.numpy as tnp

a = tnp.zeros(16).reshape((1,1,4,4))

b = tnp.zeros(16).reshape((1,4,4))
print(a)

c = tnp.concatenate((a[0], b), axis=0)

print(c)
print(tnp.expand_dims(c, axis=0))

ndarray<tf.Tensor(
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]], shape=(1, 1, 4, 4), dtype=float64)>
ndarray<tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 4, 4), dtype=float64)>
ndarray<tf.Tensor(
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]], shape=(1, 2, 4, 4), dtype=float64)>


In [2]:
import numpy as np
pred = np.array([
    [0.46137407, 0.53862596],
         
[0.6444824,  0.35551772],
      
[0.5147057,  0.48529425],
       
[0.5764453,  0.42355475],
        
[0.54298383, 0.45701614],
       
[0.55706507, 0.44293496],

[0.5488487,  0.45115134],

[0.6110012,  0.38899884],

[0.58310103, 0.41689897],
 
[0.59158623, 0.40841368],
])

actual = np.array([[.23, .77] for i in range(10)])

print(pred, actual)

[[0.46137407 0.53862596]
 [0.6444824  0.35551772]
 [0.5147057  0.48529425]
 [0.5764453  0.42355475]
 [0.54298383 0.45701614]
 [0.55706507 0.44293496]
 [0.5488487  0.45115134]
 [0.6110012  0.38899884]
 [0.58310103 0.41689897]
 [0.59158623 0.40841368]] [[0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]
 [0.23 0.77]]


In [23]:
pred = np.array([[0.65, .35] for i in range(10)])
actual = np.array([[.23, .77] for i in range(10)])
ce_loss = np.sum(-actual * np.log(pred), axis=1)
print(np.mean(ce_loss))

loss = 0.6735621

0.9074431065652464


In [26]:
pred = [
    [0.7593807, 0.2406193],
[0.65561146, 0.34438857],
[0.6296659, 0.3703341],
[0.62287325, 0.37712675],
[0.64156514, 0.3584349 ],
[0.6260284,  0.37397158],
[0.63257974, 0.36742023],
[0.6427064,  0.35729364],
[0.63016737, 0.36983263],
[0.6235071, 0.3764929],
[0.6194521,  0.38054794],
]
actual = np.array([[.23, .77] for i in range(11)])
a = 0.6881896
ce_loss = np.sum(-actual * np.log(pred), axis=1)
print(np.mean(ce_loss))


0.902166179626537


In [27]:
np.mean([0.8248588,  1.00573,    0.87402755, 0.6152879,  0.61582184, 0.6105112,
 0.59947336, 0.61753833, 0.61560225, 0.6101805,  0.5995671 ])

0.689872620909091

In [28]:
t = (1,2,3)
t[1:]

(2, 3)

In [4]:
import tensorflow as tf

tf.nn.softmax([[0.6654, -0.9503],
[0.3065, -0.2777],
[0.3060, -0.2738],
[0.3023, -0.2516],
[0.3099, -0.3034]
              ])

2021-11-25 20:01:03.558735: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.8342013 , 0.16579875],
       [0.6420332 , 0.35796675],
       [0.6410214 , 0.35897863],
       [0.6350399 , 0.36496004],
       [0.6486932 , 0.3513068 ]], dtype=float32)>

In [18]:
import tensorflow.experimental.numpy as tnp
import tensorflow as tf
# take the action 1 hot batch padd to have hidden state size entrys then reshape to match hidden state dim
# then stack with hidden_state

t = tnp.array([
    [1, 2],
    [3, 4]
])

s = tnp.array([
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]
    ],
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]
    ]
])

a= tf.reshape(tf.pad(t, [[0, 0],[0, 14]]), (2, 1, 4, 4))

s = s.reshape((None, 1, s.shape[-2],s.shape[-1]))

tf.concat((s, a), 1)

ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.